bulid-latex:
	pdflatex Vorlage.tex

clean:
	rm *.bcf *.fls *.ilg *.log *.run.xml *.toc *.aux *.fdb_latexmk *.idx *.ind
clean-all:
	rm *.bcf *.fls *.ilg *.log *.run.xml *.toc *.aux *.fdb_latexmk *.idx *.ind *.pdf
