bulid-latex: Vorlage.tex *.bib
	latexmk Vorlage.tex -pdf

clean:
	rm *.bcf *.fls *.ilg *.log *.run.xml *.toc *.aux *.fdb_latexmk *.idx *.ind *.bbl *.blg *.gz *-blx.bib
clean-all:
	rm *.bcf *.fls *.ilg *.log *.run.xml *.toc *.aux *.fdb_latexmk *.idx *.ind *.pdf
